### ISSUE TITLE
Working example with Widevine Modular

### ISSUE THREAD

**Issue by asgvard** [SamsungDForum/PlayerAVPlayDRM#4]
Hi!

We are having some issues with the integration of Widevine Modular DRM using avplay.
Followed the example from this page: [DRM Contents Playback Sequence](https://developer.samsung.com/smarttv/develop/guides/multimedia/media-playback/using-avplay.html#drm-contents-playback-sequence), but even with the testing streams from Shaka demo samples we are getting "Invalid license challenge" 500 errors from the license servers. Same content works with Shaka player. There is some difference in how EME in the browser constructs the Challenge body and how avplay does it in "ondrmevent" callback, but it's hard to understand since it's base64 encoded (even after decoding it's still not readable).

Please provide working updated example of Widevine Modular integration.

Sample Dash Manifest URL: https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd
Sample Widevine License URL: https://cwip-shaka-proxy.appspot.com/no_auth
No custom headers needed, everything works with Shaka on this combination.

Brief example of how we do it in the code:
```javascript
// Before prepareAsync
        drmParam.AppSession = uniqueId(); // random number
        drmParam.DataType = 'MPEG-DASH';

        if (parseInt(platformVersion, 10) >= 5) { // const {platformVersion} = tizen.systeminfo.getCapabilities();
          const STRINGIFIED_PARAMS = JSON.stringify(drmParam);

          webapis.avplay.setDrm(DRM_WIDEVINE, 'SetProperties', STRINGIFIED_PARAMS);
        } else {
          webapis.avplay.setDrm(DRM_WIDEVINE, 'Initialize', '');
          webapis.avplay.setDrm(DRM_WIDEVINE, 'widevine_app_session', drmParam.AppSession);
          webapis.avplay.setDrm(DRM_WIDEVINE, 'widevine_data_type', drmParam.DataType);
        }

// inside ondrmevent callback
            const decodedMessage = atob(drmData.challenge);

            const drmChallengeRequest = new XMLHttpRequest();

            drmChallengeRequest.responseType = 'arraybuffer';
            drmChallengeRequest.open('POST', this.licenseUrl, true);

            drmChallengeRequest.onload = function() {
              if (this.status === 200 && this.response) {
                const licenseParam = `${drmData.session_id}PARAM_START_POSITION${btoa(this.response)}PARAM_START_POSITION`;

                webapis.avplay.setDrm(DRM_WIDEVINE, 'widevine_license_data', licenseParam);
              } else {
                console.log('Error in license request');
              }
            };
            
            drmChallengeRequest.send(decodedMessage);
```

Here is the Diff of how Shaka player constructs license challenge request body, and how Tizen native player does that. First of all Tizen player doesn't detect TV model properly, and then there is a difference at the bottom of the request, but since it's unique at each request and encoded, it's impossible to understand which part of it is incorrect:
https://www.diffchecker.com/h8CZ5Y3X

**Comment by 606u** [comment]
`drmChallengeRequest.send(decodedMessage);` will UTF-8 escape your "string" and will basically destroy it. Convert it to byte array first:

~~~JavaScript
var buf = new Uint8Array(decodedMessage.length);
for (var i = 0; i < decodedMessage.length; ++i)
    buf[i] = decodedMessage.charCodeAt(i);
drmChallengeRequest.send(buf);
~~~

**Comment by asgvard** [comment]
Thanks, that actually worked :) At least we are not getting 500 on license request now, however still getting an error in `prepareAsync`, but this is the next step to figure out.

**Comment by 606u** [comment]
Try this:
~~~JavaScript
    function drmEventCallback(event, data) {
        if (data.name == "Challenge") {
            // request license data from license server (via HTTP POST)
            var message = atob(data.challenge); // The challenge data is base64 encoded type.   
            var buf = new Uint8Array(message.length);
            for (var i = 0; i < message.length; ++i) {
                buf[i] = message.charCodeAt(i);
            }

            var xmlhttp = new XMLHttpRequest();
            xmlhttp.responseType = "arraybuffer";
            xmlhttp.open("POST", "http://widevine-proxy.appspot.com/proxy", true);
            xmlhttp.onload = function (e) {
                if (this.status == 200) {
                    if (this.response) {
                        var buf = new Uint8Array(/*ArrayBuffer*/this.response);
                        var list = [];
                        for (var i = 0; i < buf.length; ++i)
                            list.push(String.fromCharCode(buf[i]));
                        var re = list.join('');
                        console.log("re.len", re.length);
                        var licenseParam = data.session_id + "PARAM_START_POSITION" + btoa(re) + "PARAM_START_POSITION";
                        webapis.avplay.setDrm("WIDEVINE_CDM", "widevine_license_data", licenseParam);
                    }
                }
            };
            xmlhttp.send(buf);
            //<-- server interface guide -->
        } else if (data.name == "DrmError") {
            // error handling
        }
    };
~~~
But we couldn't make it play for more than 20 seconds.

Edit: Regarding `500` -- it is likely bug in error handling in Widevine proxy. Try adding `from google.protobuf import message` on the top of `proxy.py` (run it in a console to be able to see errors).

**Comment by asgvard** [comment]
Hi, thanks for reply. I actually just tried to do similar thing, decoded the license response from ArrayBuffer to a string with:
```javascript
const base64Response = btoa(new Uint8Array(this.response)
                  .reduce((data, byte) => data + String.fromCharCode(byte), ''));

                const licenseParam =
                  `${drmData.session_id}PARAM_START_POSITION${base64Response}PARAM_START_POSITION`;

                webapis.avplay.setDrm(DRM_WIDEVINE, 'widevine_license_data', licenseParam);
```
Now the streaming works 👍 
Thanks again for tips

**Comment by orange4glace** [comment]
@asgvard Thanks for the information. That's a lot of help.
Could you please provide a full source code if possible?
I'm also trying to play the same sample you've mentioned but I can't get the `prepareCallback`. (License challenge is fine.)

Here's my partial source code. (With Tizen 5.0)

```javascript
function drmEventCallback(event, data) {
	console.log(event, data);
	log(data.name);
    // Challenge case
    if(data.name == "Challenge") {
    		console.log(data.session_id);
        // request license data from license server (via HTTP POST)
        var message = atob(data.challenge); // The challenge data is base64 encoded type.   
        console.log(message, data.challenge);
        var buf = new Uint8Array(message.length);
        for (var i = 0; i < message.length; ++i)
            buf[i] = message.charCodeAt(i);
        // <--The application should follow the server interface guide when acquiring license data -->
        var xmlhttp = new XMLHttpRequest();
        xmlhttp.responseType = "arraybuffer";
        // xmlhttp.open("POST", "http://widevine-proxy.appspot.com/proxy", true);
        xmlhttp.open("POST", "https://cwip-shaka-proxy.appspot.com/no_auth", true);

        xmlhttp.onload = function(e) {
        if (this.status == 200) {
            if (this.response) {
                	const base64Response = btoa(new Uint8Array(this.response)
                    .reduce(function (data, byte) { return data + String.fromCharCode(byte) }, ''));

                  const licenseParam =
                    data.session_id + 'PARAM_START_POSITION' + base64Response + 'PARAM_START_POSITION';
                  console.log('param = ' ,licenseParam);

                  webapis.avplay.setDrm("WIDEVINE_CDM", 'widevine_license_data', licenseParam);
            }
        }
        };
        xmlhttp.send(buf);
      //<-- server interface guide -->
    } else if(data.name == "DrmError") {
        // error handling
    }
}


function prepareCallback() {
	console.log('prep callback!');
    webapis.avplay.play();
}
var json = {
    "AppSession" : "25351",
    "DataType" : "MPEG-DASH" // The application should set DataType when the value is 'matroska_webm'.
};
var properties = JSON.stringify(json);
webapis.avplay.open(url);
webapis.avplay.setListener({
	ondrmevent:drmEventCallback,
onbufferingstart: function () {
    log("Buffering start.");
},
onbufferingprogress: function (percent) {
    log("Buffering progress data : " + percent);
},
onbufferingcomplete: function () {
    log("Buffering complete.");
},
oncurrentplaytime: function (currentTime) {
    log("Current playtime: " + currentTime);
},
onevent: function (eventType, eventData) {
    log("event type: " + eventType + ", data: " + eventData);
},
onstreamcompleted: function () {
    log("Stream Completed");
    this.stop();
}.bind(this),
onerror: function (eventType) {
    log("event type error : " + eventType);
}
});
webapis.avplay.setDrm("WIDEVINE_CDM", "SetProperties", properties);
webapis.avplay.setDisplayRect(0, 0, 1920, 1080);
webapis.avplay.prepareAsync(prepareCallback);
```

Thanks.

**Comment by 606u** [comment]
In our case the culprit for 20-seconds playback turned out to be Widevine licensing proxy server. Nevertheless, same code works on _some_ years/models and does not work on _other_ years/models. Which year/model you have issues with? Verify if you've properly **whitelisted all referenced domains** in `config.xml`.

**Comment by orange4glace** [comment]
@606u Thanks for your sharing! I just tried with your code and it WORKED!

~~But there're some problem. It would be very appreciated if you have ever encountered with those problems and share your experience.~~

(**Updated**)
1. ~~There's a long stall on calling `prepareAsync`. The TV app calls *.mpd* file over the network immediately. but after that, it takes 10 seconds before it calls License server.~~


2. ~~When it first calls `prepareAsync`,  *Buffering start* event fires and it starts buffering. Then *Buffering end* events is called. But it never play after that. I tried to call `avplay.play()` on `onbufferingcomplete` event but `InvalidStateError` occurs.
On the second `prepareAsync` call, it starts playing normally sometimes or it repeats the same error sometimes.~~

**NVM. I was calling `prepare()` and `prepareAsync()` at the same time. :P**

And as you mentioned that your code worked on some *years/models* and does not work on *other years/models*. How does that end up with? It seems that it's a total **nightmare**. Like, if it's true, it seems that making a useful app with using *AVPlay* is completely impossible.

BTW, my testing device model is *QN65Q90RAFXKR* , which came out on 2019.

Thanks.

**Comment by 606u** [comment]
Well, our issue with some models playing Widevine-protected content, while other models not playing same content, is still open.

**Comment by randomfog42** [comment]
``` ts
import * as b64ab from 'base64-arraybuffer';
...
...

// WIDEVINE_CDM
async handleDrmEvent(event, data) {
  if (data.name === 'Challenge') {
    const response = await fetch(
      licenseServer,
      {
        method: 'post',
        body: b64ab.decode(data.challenge)
      }
    );

    if (response.ok) {
      const buffer = await response.arrayBuffer();
      const encode = b64ab.encode(buffer);
      const licenseParam = `${data.session_id}PARAM_START_POSITION${encode}PARAM_START_POSITION`;
      this.webapis.avplay.setDrm('WIDEVINE_CDM', 'widevine_license_data', licenseParam);
    } else {
      console.error('handleWidevineEvent', response.status);
    }
}
```

**Comment by rabinmahatozee** [comment]
Can anyone provide me the working example of widevine modular in Tizen 2.4

**Comment by zamroni111** [comment]
> Hi, thanks for reply. I actually just tried to do similar thing, decoded the license response from ArrayBuffer to a string with:
> 
> ```js
> const base64Response = btoa(new Uint8Array(this.response)
>                   .reduce((data, byte) => data + String.fromCharCode(byte), ''));
> 
>                 const licenseParam =
>                   `${drmData.session_id}PARAM_START_POSITION${base64Response}PARAM_START_POSITION`;
> 
>                 webapis.avplay.setDrm(DRM_WIDEVINE, 'widevine_license_data', licenseParam);
> ```
> 
> Now the streaming works 👍 Thanks again for tips

can you share the full code?
i got below error on prepareAsync
"in getErrorObjectLocal code:15,name:InvalidAccessError NaNmessage:PLAYER_ERROR_CONNECTION_FAILED"

**Comment by zamroni111** [comment]
This is my code that works in tizen 6.5 TV.
the javascript codes are inlined in this index.html:
`<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
	<script src="$WEBAPIS/webapis/webapis.js"></script>
</head>

<body style="color:lime;font-size:x-large">
	<object id="av-player" type="application/avplayer"></object>

	<script>
"use strict";
window.addEventListener('tizenhwkey', async function(e) {
	if (e.keyName == "back") {
		try {
			await webapis.avplay.stop();
			await webapis.avplay.close();
			console.log("CLEAN");
		}
		catch (myexception) {}
		tizen.application.getCurrentApplication().exit();
	}
});

function base64ToBytes(base64) {
	return Uint8Array.from(atob(base64), (m) => m.codePointAt(0));
}

function bytesToBase64(bytes) {
	return btoa(Array.from(bytes, (byte) => String.fromCodePoint(byte), ).join(""));
}

window.onload = async function() {
	await webapis.avplay.open("https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest_1080p.mpd");
///	await webapis.avplay.open("https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest.mpd");

	await webapis.avplay.setListener({
		ondrmevent: async function(event, data) {
			if (data.name == "Challenge") {
				let myfetch = await fetch("https://drm-widevine-licensing.axtest.net/AcquireLicense", {
					method: "POST",
					headers: {
						"X-AxDRM-Message": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjoxLCJjb21fa2V5X2lkIjoiYjMzNjRlYjUtNTFmNi00YWUzLThjOTgtMzNjZWQ1ZTMxYzc4IiwibWVzc2FnZSI6eyJ0eXBlIjoiZW50aXRsZW1lbnRfbWVzc2FnZSIsImtleXMiOlt7ImlkIjoiOWViNDA1MGQtZTQ0Yi00ODAyLTkzMmUtMjdkNzUwODNlMjY2IiwiZW5jcnlwdGVkX2tleSI6ImxLM09qSExZVzI0Y3Iya3RSNzRmbnc9PSJ9XX19.4lWwW46k-oWcah8oN18LPj5OLS5ZU-_AQv7fe0JhNjA"
					},
					body: base64ToBytes(data.challenge)
				});
				let myarray = new Uint8Array(await myfetch.arrayBuffer());
				let LicenseParam = data.session_id + "PARAM_START_POSITION" + bytesToBase64(myarray) + "PARAM_START_POSITION";
				webapis.avplay.setDrm("WIDEVINE_CDM", "widevine_license_data", LicenseParam);
			}
		},
		onbufferingstart: function() {
			/////console.log("Buffering start.");
		},
		onbufferingprogress: function(percent) {
			///////////console.log("Buffering progress data : " + percent);
		},
		onbufferingcomplete: function() {
			/////console.log("Buffering complete.");
		},
		oncurrentplaytime: function(vtime) {
			//////console.log("Current playtime: " + vtime);
		},
		onstreamcompleted: function() {},
		onevent: function(eventType, eventData) {
			console.log("GGGGGGGGG event type: " + eventType + ", data: " + eventData);
		},
		onerror: function(errorData) {
			console.log("event type error : " + errorData);
		},
		onerrormsg: function(eventid, errorMsg) {
			console.log("TTTTT event type: " + eventid + ", data: " + errorMsg);
		},
		onsubtitlechange: function(duration, subtitles, type, attributes) {
			//////console.log("XXXXXXX duration=" + duration + ", subtitles=" +  subtitles + ", type=" + type + ", attr=" + JSON.stringify(attributes));
		},
		onhttperrorevent: function(eventType, eventData) {
			console.log(eventType + eventData);
		},
		onuserdata: function(type, attrdata) {
			console.log(type + "\n" + attrdata);
		},
		onstreamcompleted: function() {}
	});

	var drmjson = {
		"DeleteLicenseAfterUse": true,
		"AppSession": "mysession",
		"DataType": "MPEG-DASH"
	};
	await webapis.avplay.setDrm("WIDEVINE_CDM", "SetProperties", JSON.stringify(drmjson));
	await webapis.avplay.setDisplayRect(0, 0, 1920, 1080);
	await webapis.avplay.setStreamingProperty("ADAPTIVE_INFO", "FIXED_MAX_RESOLUTION=3840X2160");
	await webapis.avplay.setDisplayMethod("PLAYER_DISPLAY_MODE_AUTO_ASPECT_RATIO");
	await webapis.avplay.prepareAsync(
		async function(successobj) {
				console.log("JJJJJJJJJJJJJ " + webapis.avplay.getState());
				await webapis.avplay.play();
				console.log("KKKKKKKKKKKKKK " + webapis.avplay.getState());

				var totalTrackInfo = webapis.avplay.getTotalTrackInfo();
				console.log(totalTrackInfo);
				let i;

				let j = -1;
				for (i in totalTrackInfo) {
					if (totalTrackInfo[i].type === "AUDIO") {
						j = i;
						if ((JSON.parse(totalTrackInfo[i].extra_info)).language.toLowerCase().startsWith("en")) break;
					}
				}
				if (j !== -1) {
					console.log(totalTrackInfo[j]);
					webapis.avplay.setSelectTrack("AUDIO", totalTrackInfo[j].index);
				}

				j = -1;
				for (i in totalTrackInfo) {
					let vextrainfo = JSON.parse(totalTrackInfo[i].extra_info.toLowerCase());
					if (totalTrackInfo[i].type === "TEXT" && vextrainfo.fourcc.search(/plain|stpp|vtt/) === -1) {
						console.log(vextrainfo);
						if (vextrainfo.track_lang.startsWith("en")) {
							j = i;
							break;
						}
					}
				}
				if (j !== -1) {
					console.log(totalTrackInfo[j]);
					webapis.avplay.setSelectTrack("TEXT", totalTrackInfo[j].index);
				}
			},
			function(errorobj) {
				console.log("OOOOOOOOOOOO " + webapis.avplay.getState() + "\n" + JSON.stringify(errorobj));
			}
	);
}
	</script>
</body>
</html>`

config.xml:
`<?xml version="1.0" encoding="UTF-8"?>
<widget xmlns:tizen="http://tizen.org/ns/widgets" xmlns="http://www.w3.org/ns/widgets" id="http://yourdomain/wvplayer" version="1.0.0" viewmodes="maximized">
    <access origin="*" subdomains="false"></access>
    <tizen:application id="t5RA7lYGm3.wvplayer" package="t5RA7lYGm3" required_version="2.3"/>
    <content src="index.html"/>
    <feature name="http://tizen.org/feature/screen.size.normal.1080.1920"/>
    <icon src="widevine.jpg"/>
    <tizen:metadata key="http://tizen.org/metadata/app_ui_type/base_screen_resolution" value="extensive"/>
    <name>wvplayer</name>
    <tizen:privilege name="http://developer.samsung.com/privilege/drmplay"/>
    <tizen:profile name="tv-samsung"/>
    <tizen:setting screen-orientation="landscape" context-menu="enable" background-support="disable" encryption="enable" install-location="auto" hwkey-event="enable" sound-mode="shared"/>
</widget>
`

**Comment by zamroni111** [comment]
i put working example of widevine player for tizen 6.5 in this repo:
https://github.com/zamroni111/samsung_avplay_widevine

The HTTP response's content-type header must be application/dash+xml.
MPD such as "https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd" is unaplayable due to incorrect content-type.

Additional features:
1. Subtitle display using HTML table element
2. Playback button control:
a. play/pause button
b. up button: fast forward 2/4/8x
c. down & middle button: set 1x playback
d. left & right button: seek -/+ 10 seconds
e. channel up & down button: subtitle switcher
f. channel guide button: show/hide subtitle
g. return button: proper stop, close then exit.
3. Status text display: current play position, video duration, playback speed, subtitle id.

**Comment by AswinKambadathil** [comment]
@zamroni111  @taihoon @606u @asgvard @orange4glace Currently, I am developing an IPTV app for Samsung, and I’m encountering an issue with the HLS URL using Widevine license. I’m getting an 'invalid access' error. The POST request is giving the response properly. Sometimes it plays for a while, but when I launch the app again, it doesn’t play. Can anyone explain why this happens?"

**Comment by zamroni111** [comment]
> [@zamroni111](https://github.com/zamroni111) [@taihoon](https://github.com/taihoon) [@606u](https://github.com/606u) [@asgvard](https://github.com/asgvard) [@orange4glace](https://github.com/orange4glace) Currently, I am developing an IPTV app for Samsung, and I’m encountering an issue with the HLS URL using Widevine license. I’m getting an 'invalid access' error. The POST request is giving the response properly. Sometimes it plays for a while, but when I launch the app again, it doesn’t play. Can anyone explain why this happens?"

Avplay doesn't support drm for hls.

**Comment by AswinKambadathil** [comment]
@zamroni111 But it is playing while I am playing in your code. Instead of Dash I was giving HLS

**Comment by AswinKambadathil** [comment]
@zamroni111 But same situation for one time its playing and if I am exiting the app and playing again it doesn,t play

**Comment by zamroni111** [comment]
Probably the ok one was for non encrypted hls segment, e.g. ads.

I never able to make hls drm works in avplay, either with playready and widevine.

For widevine, avplay docs explicitly only mentions dash and mkv.
https://developer.samsung.com/smarttv/develop/api-references/samsung-product-api-references/avplay-api.html#AVPlayDrmOperation

**Comment by AswinKambadathil** [comment]
@zamroni111 Now I tried with Dash url and all features are working fine. Thankyou

**Comment by AswinKambadathil** [comment]
@zamroni111 How can I make the Widevine drm work for older version tv. Now for my 2024 model tv its working but for 2022 model its not playing

**Comment by zamroni111** [comment]
> [@zamroni111](https://github.com/zamroni111) How can I make the Widevine drm work for older version tv. Now for my 2024 model tv its working but for 2022 model its not playing

I made that repo using tizen 6.5 g70nc, which should be same as 2022 tv series.
Have you verified the certificate thing?

**Comment by AswinKambadathil** [comment]
@zamroni111 No I haven't checked the certificate. I will check that and try.

**Comment by AswinKambadathil** [comment]
I got it loaded in new TV. Now I am trying to integrate in tizen 5.5 version tv and ondrmevent: I am getting data as drmerror
code: "8"
message: "Fail to initialize EME session!"
name: "DrmError"

Why is this error comming, can anyone help in doing this @zamroni111

**Comment by zamroni111** [comment]
> I got it loaded in new TV. Now I am trying to integrate in tizen 5.5 version tv and ondrmevent: I am getting data as drmerror code: "8" message: "Fail to initialize EME session!" name: "DrmError"
> 
> Why is this error comming, can anyone help in doing this [@zamroni111](https://github.com/zamroni111)

Do the manifest and drm url work in newer tizen?

You can try it in my shaka web player and open browser developer tool (f12) to see the http layer details
https://ma-zamroni.blogspot.com/2021/03/simple-shaka-player.html

**Comment by AswinKambadathil** [comment]
Yes, Its working in newer version Tvs but older TVs are giving this error.

I have tried giving my play url and Licence url to your shaka web player and it is not playing.

Can you give some suggestion to make it play in older model TVs before 2021

**Comment by AswinKambadathil** [comment]
Sorry Its actually playing in your shaka player when I give the licence url and playurl .
Can you share me a specific code only for the player.

**Comment by zamroni111** [comment]
> Sorry Its actually playing in your shaka player when I give the licence url and playurl . Can you share me a specific code only for the player.


`
<p>
	Shaka Player documentation:<a href="https://shaka-player-demo.appspot.com/docs/api/index.html" target="_blank">https://shaka-player-demo.appspot.com/docs/api/index.html</a>
</p>
<script src="https://cdn.jsdelivr.net/npm/shaka-player@4.9/dist/shaka-player.compiled.js"></script>
<style>
a {
	color: #33c4ff;
}

video::-webkit-media-text-track-display {
	padding-bottom: 1%;
}

video::cue {
	background-color: rgba(0, 0, 0, 0);
	text-shadow: 2px 1px black;
}

option,
select,
input {
	color: #0000FF;
	font-size: large
}

button {
	font-size: large
}
</style>
<p>
	Media URL (MPEG-DASH *.mpd or HLS *.m3u8):<br />
	<input type="text" style="box-sizing:border-box;width:100%" id="mediaurl" autocomplete="off" value="https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd" />
	<br>Subtitle: <input type="text" style="box-sizing:border-box;width:100%" id="substitleurl" autocomplete="off" value="">
</p>
<p>
	DRM Type & License URL:<br />
	<select id="drmtype">
		<option value="com.apple.fairplay">Apple Fairplay</option>
		<option value="com.widevine.alpha" selected>Google Widevine</option>
		<option value="com.microsoft.playready">Microsoft Playready</option>
		<option value="org.w3.clearkey">W3C Clear Key</option>
		<option value="">NO DRM</option>
	</select>
	<input type="text" style="box-sizing:border-box;width:100%" id="drmurl" autocomplete="off" value="https://cwip-shaka-proxy.appspot.com/no_auth" />
</p>
<p>
	<input type="button" value="PLAY" onclick='javascript:debuginfo.innerHTML="";playmedia()' />
	<input type="button" value="Clear" onclick='javascript:mediaurl.value="";drmurl.value="";substitleurl.value="";drmtype.options.selectedIndex=4' />
	<input type="button" value="DEBUG" onclick="javascript:debugvalue()" />
</p>
<video id="myvideo" width="100%" controls></video><br />
<p id="debuginfo" style="font-family:monospace;font-size:small"></p>

<script>
"use strict";
if (navigator.userAgent.search(/firefox/i) !== -1) shaka.polyfill.installAll();
if (navigator.userAgent.search(/mobile/i) === -1) myvideo.width = 640;

var player = new shaka.Player();

async function playmedia() {
	try {
		await player.unload();
		await player.detach();
	}
	catch (e) {}
	await player.attach(document.getElementById("myvideo"));

	let var_drm = drmtype.options[drmtype.options.selectedIndex].value.trim();
	let playerconfig = {
		preferredAudioLanguage: "en",
		preferredTextLanguage: "en",
		streaming: {
			//////preferNativeHls: true
		},
		drm: {
			advanced: {
				'com.widevine.alpha': {
					persistentStateRequired: true,
					distinctiveIdentifierRequired: true
				},
				'com.microsoft.playready': {
					persistentStateRequired: true,
					distinctiveIdentifierRequired: true
				},
			}
		}

	};
	if (var_drm != "") {
		playerconfig.drm.servers = {};
		playerconfig.drm.servers[var_drm] = drmurl.value.trim();
	}
	///alert(JSON.stringify(playerconfig));
	player.configure(playerconfig);
	await player.load(mediaurl.value.trim()); ///, 0);//, "application/vnd.apple.mpegurl");
	if (substitleurl.value.trim() !== "") await player.addTextTrackAsync(substitleurl.value.trim(), "en", "captions"); ///, "application/ttml+xml");
	await player.setTextTrackVisibility(true);
	///////await player.goToLive();
	await debugvalue();
	///	await myvideo.play();
}

async function debugvalue() {
	debuginfo.innerHTML = "Text tracks:<br>" + JSON.stringify(player.getTextLanguagesAndRoles()).replace(/\x7D\x2C/g, "},<br>");
	debuginfo.innerHTML += "<br><br>Audio tracks:<br>" + JSON.stringify(player.getAudioLanguagesAndRoles()).replace(/\x7D\x2C/g, "},<br>");
	debuginfo.innerHTML += "<br><br>Variant tracks:<br>" + JSON.stringify(player.getVariantTracks().reverse()).replace(/\x7D\x2C/g, "},<br><br>").replace(/\x2c\x22/g, ', "');
}
//playmedia();
</script>`

**Comment by AswinKambadathil** [comment]
category: 6
code: 6001
data: []
handled: false
message: "Shaka Error 6001"
severity: 2
stack: "Error: Shaka Error 6001↵    at new T (https://cdn.jsdelivr.net/npm/shaka-player@4.9/dist/shaka-player.compiled.js:89:311)↵    at Da.h (https://cdn.jsdelivr.net/npm/shaka-player@4.9/dist/shaka-player.compiled.js:263:184)↵    at Ha (https://cdn.jsdelivr.net/npm/shaka-player@4.9/dist/shaka-player.compiled.js:21:299)↵    at Ia.next (https://cdn.jsdelivr.net/npm/shaka-player@4.9/dist/shaka-player.compiled.js:22:91)↵  



I am getting this error when I am trying to play

**Comment by zamroni111** [comment]
Please try using code in attachment.
Previous copy paste might change some line as html code.

[shaka.txt](https://github.com/user-attachments/files/18746540/shaka.txt)

**Comment by AswinKambadathil** [comment]
After trying that also I am getting the same error

**Comment by zamroni111** [comment]
Shaka error 6001 is drm error
https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html

Probably you can add advanced drm config in shaka config.
First 4 config items in table https://shaka-player-demo.appspot.com/docs/api/shaka.extern.html#.AdvancedDrmConfiguration

My laptop is broken so I can't type much details in phone

**Comment by AswinKambadathil** [comment]
Ok thankyou I will check with that
